# Example irc bridge.
#irc-bridges:
#    test:
#        ssl: false
#        host: localhost
#        port: 6667
#        nick: DuckChat
#        password: ''
#        username: 'bot'
#        realm: 'localhost'
#        messageFormat: '[global %s@IRC] %s'
#        actionFormat: '[global] *%s@IRC %s'
#        channels:
#            global: '#yourchannel'
                
messages:
        irc:
                playerlist:
                        header: '%2$d players playing Minecraft on %1$d servers.'
                        line: '%s(%d): %s'
