# Name of JGroups cluster.
# 
# Sets the name of the jgroups cluster to connect to, this must be the same
# on all the servers you want to be in the same cluster.
#
# clusterName: duckchat

# Name of this server, defaults to using server-name from server.properties. 
# If you don't wish to set server-name in server.properties, or you wish
# to use a different value here, uncomment this.
# nodename: Unknown

# Default channel name.
defaultChannel: global

# Store players by UUID.
#
useUUIDs: true

# Use IPv4
useIPv4: true

# Address to use for multicast networking
bindAddress: 127.0.0.1

# Shortcuts for accessing channels.
# Include a space in the shortcut if you wish it to require a space.
shortcuts:
        '! ': global

# Network config
# Should not be needed unless you want to try using strange configurations.
#
# network: udp.xml

# List of channels.

# format parameters.
# 1 - Channel name
# 2 - Nodename
# 3 - World name
# 4 - player name
# 5 - player prefix
# 6 - player display name
# 7 - player suffix.
# 8 - Message or action.
channels:
        global:
                owned: false
                localAutoJoin: false
                messageFormat: '[%1$s %6$s] %8$s'
                actionFormat: '[%1$s] %6$s %8$s'
                globalAutoJoin: true
#                permission: some.permission
# Uncomment and rename this for a locally owned channel
#        local:
#                owned: true
#                localAutoJoin: true
#                globalAutoJoin: false
#                permission: some.permission